name: CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn build
      - run: yarn lint
      - run: yarn pa11y
      - run: yarn html-proofer
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@https://github.com/italia/cloud.italia.it-site.git
          yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}