name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn build
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/italia/cloud.italia.it-site.git
          echo cloud.italia.it > public/CNAME

          yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
